version: "3.4"

services:
  datamanagement:
    image: docker.io/predictionbotservice/data-management-service:latest

  modeltrainer:
    image: docker.io/predictionbotservice/model-trainer-service:latest

  predictionservice:
    image: docker.io/predictionbotservice/prediction-service:latest

  operationservice:
    image: docker.io/predictionbotservice/operation-service:latest

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: predictionbot
      MYSQL_USER: predictionbot
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
