version: "3.4"

services:
  datamanagement:
    image: ${DOCKER_REGISTRY-}datamanagement
    build:
      context: .
      dockerfile: DataManagement/Dockerfile

  modeltrainer:
    image: ${DOCKER_REGISTRY-}modeltrainer
    build:
      context: .
      dockerfile: ModelTrainer/Dockerfile

  predictionservice:
    image: ${DOCKER_REGISTRY-}predictionservice
    build:
      context: .
      dockerfile: PredictionService/Dockerfile

  operationservice:
    image: ${DOCKER_REGISTRY-}operationservice
    build:
      context: .
      dockerfile: OperationService/Dockerfile

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: predictionbot
      MYSQL_USER: predictionbot
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
